# INSERCIONES EN PERSONA;
insert into persona (nombre,dni,fecha) values (laura,31651161,19850701); 
insert into persona (nombre,dni,fecha) values (damian,30987777,19851025);
insert into persona (nombre,dni,fecha) values (estefania,31662391,19850714);
insert into persona (nombre,dni,fecha) values (manuel,32000000,19850205);
insert into persona (nombre,dni,fecha) values (nicolas,30678887,19851119);
insert into persona (nombre,dni,fecha) values (moe,31650000,19851101);
insert into persona (nombre,dni,fecha) values (laura,31988811,19900701);
insert into persona (nombre,dni,fecha) values (laura,28990009,20000701);
insert into persona (nombre,dni,fecha) values (estefania,12000009,20070607);
# INSERCIONES EN ALUMNO;
insert into alumno (nombre,padron) values (laura,85597);
insert into alumno (nombre,padron) values (estefania,85999);
insert into alumno (nombre,padron) values (juan,70000);
insert into alumno (nombre,padron) values (aleee,87000);
insert into alumno (nombre,padron) values (estefania,89987);
insert into alumno (nombre,padron) values (aleee,10001);
insert into alumno (nombre,padron) values (damian,76543);
insert into alumno (nombre,padron) values (damian,00001);
insert into alumno (nombre,padron) values (moe,98765);
#INSERCIONES EN EMPLEADO;
insert into empleado (nombre,dni,ocupacion) values (moe,31650000,pintor);
insert into empleado (nombre,dni,ocupacion) values (aleee,28134211,decano);
insert into empleado (nombre,dni,ocupacion) values (rosito,18976111,ayudante);
insert into empleado (nombre,dni,ocupacion) values (laura,31651161,presidenta);
insert into empleado (nombre,dni,ocupacion) values (manuel,32000000,marinerito);
insert into empleado (nombre,dni,ocupacion) values (roberto,123452,galan);
#CONSULTAS;
#select persona.*,alumno.* from persona join alumno on persona.nombre = alumno.nombre;
#select persona.*,empleado.* from persona join empleado on persona.nombre = empleado.nombre;
#select persona.*,empleado.* from persona join empleado on persona.dni = empleado.dni;
#select alumno.*,empleado.* from alumno join empleado on alumno.nombre = empleado.nombre;
#select persona.*,alumno.* from persona join alumno on persona.nombre = alumno.nombre order by persona.dni;#el indice primario es un hash no deberia funcionar;
#select persona.*,alumno.* from persona join alumno on persona.nombre = alumno.nombre where persona.nombre < maria;#deberian irse nico y moe;
select persona.*,empleado.* from persona join empleado on persona.dni = empleado.dni order by empleado.dni;
#select persona.*,empleado.* from persona join empleado on persona.dni = empleado.dni where persona.nombre = laura and persona.dni = 8;#no debe traer nada;
#select persona.*,empleado.* from persona join empleado on persona.dni = empleado.dni where persona.nombre = laura or persona.dni = 8;#debe traer registros con laura;
#select persona.*,empleado.* from persona join empleado on persona.dni = empleado.dni where persona.nombre = moe and persona.dni = 31650000;#trae a moe;
#JOIN TRIPLE;
#select persona.*,alumno.*,empleado.* from persona join alumno on persona.nombre = alumno.nombre join empleado on persona.nombre = empleado.nombre;
#select persona.*,alumno.*,empleado.* from persona join alumno on persona.nombre = alumno.nombre join empleado on alumno.nombre = empleado.nombre;
#select persona.*,alumno.*,empleado.* from persona join alumno on persona.nombre = alumno.nombre join empleado on persona.nombre = empleado.nombre where persona.nombre = aleee;
#select persona.*,alumno.*,empleado.* from persona join alumno on persona.nombre = alumno.nombre join empleado on persona.nombre = empleado.nombre where persona.nombre > laura and persona.nombre < nico;
