insert into PERSONA (nombre,dni,fecha) values ('Mazinger',1,19911111);
insert into PERSONA (nombre,dni,fecha) values ('Robocop',2,19921010);
insert into PERSONA (nombre,dni,fecha) values ('Boby Goma',3,19931213);
insert into PERSONA (nombre,dni,fecha) values ('Aureliano Buendia',4,18100913);
insert into PERSONA (nombre,dni,fecha) values ('Coornelio Saavedra',5,18100404);
insert into PERSONA (nombre,dni,fecha) values ('Juan Jose Paso',6,18101212);
insert into PERSONA (nombre,dni,fecha) values ('Mariano Moreno',7,18101111);
insert into PERSONA (nombre,dni,fecha) values ('Miguel de Azcuenaga',8,18100930);
insert into PERSONA (nombre,dni,fecha) values ('Manuel Alberti',9,18100602);
insert into PERSONA (nombre,dni,fecha) values ('Juan Larrea',10,18100804);
insert into PERSONA (nombre,dni,fecha) values ('Juan Jose Castelli',11,18100421);
insert into PERSONA (nombre,dni,fecha) values ('Manuel Belgrano',12,18101004);
insert into PERSONA (nombre,dni,fecha) values ('Domingo Matheu',13,18100204);
insert into PERSONA (nombre,dni,fecha) values ('Blasmac',14,19890807);
insert into PERSONA (nombre,dni,fecha) values ('Damian "Fantastico" Pisaturo',15,19851010);
insert into PERSONA (nombre,dni,fecha) values ('Laura Maria "La Tigresa Hermitania" Rodriguez',16,19851110);
insert into PERSONA (nombre,dni,fecha) values ('Estefania "Patrocinio Existencial" Caravatti',17,19851011);
insert into PERSONA (nombre,dni,fecha) values ('Manuel "Homosexual Acrucerado" Garcia Cabrera',18,19851111);
insert into PERSONA (nombre,dni,fecha) values ('Nicolas "Fantoche Ponzonioso" Fantone',19,19851212);
insert into PERSONA (nombre,dni,fecha) values ('Nahuel "Falanges Sangrantes" Grisolia',21,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',22,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',220,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',456,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',9461,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',89461,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',888,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',9999,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',145318,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',-685,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',-992,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',318618,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',-78972,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',45645,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',645642,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',226,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',2001,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',2002,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',8788,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',666,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',7897892,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',320,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',741,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',852,19860516);
insert into PERSONA (nombre,dni,fecha) values ('Este es un texto bastante largo, como para demostrar que es posible insertar textos bastante extensos en nuestros indices, sin que se resquebrajen los simientos sobre los que se amolda la aplicacion',963,19860516);
#delete from PERSONA where DNI > 4 and DNI <= 13; #Borra todos los integrantes de la Primera Junta;
#delete from PERSONA where FECHA > 19901010 and NOMBRE <= 'Carlos "El Turco Madrugador" Morientes'; #Borra a Boby Goma;
#delete from PERSONA where NOMBRE = 'Estefania "Patrocinio Existencial" Caravatti'; #La borro a Tifi porque me cae mal;
#delete from PERSONA where DNI = 20; #No borra nada (DNI inexistente);
#delete from PERSONA where NOMBRE = 'Carla "Motivacion Delictiva" Pietrorini"' or DNI = 1; #Borra a Mazinger;
#insert into PERSONA (nombre,dni,fecha) values ('Tifi',17,19851011); #La vuelvo a insertar a Tifi, porque me entro algo de culpa.;
#delete from PERSONA where FECHA = 19851111; #Y mejor lo borro a Manu, que es un zurdo;
#update PERSONA set NOMBRE = 'Mazinger Z' where DNI = 1; #Cambia Mazinger por Mazinger Z;
#update PERSONA set NOMBRE = 'blaSmac' , FECHA = 20071231 where DNI = 14; #Cambia la fecha y el nombre de Blasmac;
#update PERSONA set NOMBRE = 'Manuel "Conmocion Post-Crucero" Cabrera' where NOMBRE = 'Manuel "Homosexual Acrucerado" Garcia Cabrera'; #Cambia el nombre de Manu;
#update PERSONA set FECHA = 20071209 where FECHA = 19931213; #Cambia la fecha de Boby Goma;
#update PERSONA set NOMBRE = 'Mandioca Sideral' where FECHA > 20071208; #Cambia el nombre de Boby Goma a Mandioca Sideral;
#delete from PERSONA where DNI = 9; # Borra a Manuel Alberti (que era un cura un tanto pedofilo);
#update PERSONA set NOMBRE = 'Pedofilia papal' where DNI = 9; #No actualiza nada (acabo de borrarlo al cura toca-nenes);
#update PERSONA set FECHA = 18100525 where DNI > 4 and DNI < 14; #Actualiza la fecha de todos los integrantes de la primera junta al 25 de Mayo de 1810;
#update PERSONA set DNI = 20 where DNI = 15; #Cambia el DNI de Dami;
#insert into PERSONA (nombre,dni,fecha) values ('Hans Castorp',15,19880829); #Inserta a Hans Castorp con el DNI de Dami;
